export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'

export const LOAD_ADMIN_ARTISTS = 'LOAD_ADMIN_ARTISTS'
export const LOAD_ADMIN_ARTIST_NAMES = 'LOAD_ADMIN_ARTIST_NAMES'
export const LOAD_ADMIN_SONGS = 'LOAD_ADMIN_SONGS'
export const SET_ADMIN_TOKEN = 'SET_ADMIN_TOKEN'

export const LOAD_LATEST_SONGS = 'LOAD_LATEST_SONGS'
export const LOAD_LATEST_ARTISTS = 'LOAD_LATEST_ARTISTS'