export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'

export const LOAD_ADMIN_ARTISTS = 'LOAD_ADMIN_ARTISTS'
export const SET_ADMIN_ARTISTS_CHANGED = 'SET_ADMIN_ARTISTS_CHANGED'
export const SET_ADMIN_ARTISTS_SEARCH = 'SET_ADMIN_ARTISTS_SEARCH'

export const LOAD_ADMIN_ARTIST_NAMES = 'LOAD_ADMIN_ARTIST_NAMES'

export const LOAD_ADMIN_SONGS = 'LOAD_ADMIN_SONGS'
export const SET_ADMIN_SONGS_CHANGED = 'SET_ADMIN_SONGS_CHANGED'
export const SET_ADMIN_SONGS_SEARCH = 'SET_ADMIN_SONGS_SEARCH'

export const SET_ADMIN_TOKEN = 'SET_ADMIN_TOKEN'
export const SET_ADMIN_VERIFIED = 'SET_ADMIN_VERIFIED'

export const LOAD_LATEST_SONGS = 'LOAD_LATEST_SONGS'
export const LOAD_LATEST_ARTISTS = 'LOAD_LATEST_ARTISTS'
export const LOAD_TOP_SONGS = 'LOAD_TOP_SONGS'

export const LOAD_SONGS = 'LOAD_SONGS'
export const SET_SONGS_GENRE = 'SET_SONGS_GENRE'
export const SET_SONGS_PAGE = 'SET_SONGS_PAGE'

export const LOAD_ARTISTS = 'LOAD_ARTISTS'

export const LOAD_SEARCH_SONGS = 'LOAD_SEARCH_SONGS'
export const LOAD_SEARCH_ARTISTS = 'LOAD_SEARCH_ARTISTS'
export const SET_SEARCH_TAB = 'SET_SEARCH_TAB'
export const SET_SEARCH = 'SET_SEARCH'